# Generated by Django 4.2.10 on 2024-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestellListe',
            fields=[
                ('sap_bestell_nr_field', models.IntegerField(db_column='SAP_Bestell_Nr.', primary_key=True, serialize=False)),
                ('modell', models.CharField(db_column='Modell', max_length=20)),
                ('typ', models.CharField(db_column='Typ', max_length=20)),
                ('menge', models.IntegerField(db_column='Menge')),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
                ('inventarnummern_von_bis', models.TextField(blank=True, db_column='Inventarnummern Von-Bis', null=True)),
                ('geliefert', models.CharField(db_column='Geliefert', max_length=1)),
                ('geliefert_anzahl', models.IntegerField(blank=True, db_column='Geliefert_Anzahl', null=True)),
            ],
            options={
                'db_table': 'Bestell_Liste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investmittelplan',
            fields=[
                ('klinik_ou', models.CharField(db_column='Klinik_OU', max_length=3, primary_key=True, serialize=False)),
                ('investmittel_jahresanfang_in_euro', models.DecimalField(db_column='Investmittel_Jahresanfang_in_Euro', decimal_places=2, max_digits=6)),
                ('investmittel_übrig_in_euro', models.DecimalField(blank=True, db_column='Investmittel_übrig_in_Euro', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'Investmittelplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lagerliste',
            fields=[
                ('inventarnummer', models.IntegerField(db_column='Inventarnummer', primary_key=True, serialize=False)),
                ('klinik', models.CharField(blank=True, db_column='Klinik', max_length=20, null=True)),
                ('typ', models.CharField(db_column='Typ', max_length=20)),
                ('modell', models.CharField(db_column='Modell', max_length=20)),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
                ('investmittel', models.CharField(db_column='Investmittel', max_length=4)),
                ('ausgabe', models.DateTimeField(blank=True, db_column='Ausgabe', null=True)),
                ('ausgegeben', models.CharField(db_column='Ausgegeben', max_length=1)),
            ],
            options={
                'db_table': 'Lagerliste',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
