# Generated by Django 4.2.10 on 2024-02-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='upfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='/home/adminukd/')),
            ],
        ),
    ]
