# Generated by Django 4.2.10 on 2024-02-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0004_upfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upfile',
        ),
    ]
