# Generated by Django 4.2.10 on 2024-02-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='WebapplicationUser',
        ),
        migrations.DeleteModel(
            name='WebapplicationUserGroups',
        ),
        migrations.DeleteModel(
            name='WebapplicationUserUserPermissions',
        ),
    ]
