# Generated by Django 4.2.10 on 2024-02-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0008_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLagerliste',
            fields=[
                ('inventarnummer', models.IntegerField(db_column='Inventarnummer', primary_key=True, serialize=False)),
                ('klinik', models.CharField(blank=True, db_column='Klinik', max_length=20, null=True)),
                ('typ', models.CharField(db_column='Typ', max_length=20)),
                ('modell', models.CharField(db_column='Modell', max_length=20)),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
                ('investmittel', models.CharField(db_column='Investmittel', max_length=4)),
                ('ausgabe', models.DateTimeField(blank=True, db_column='Ausgabe', null=True)),
                ('ausgegeben', models.CharField(db_column='Ausgegeben', max_length=1)),
            ],
            options={
                'db_table': 'Temp_Lagerliste',
                'managed': False,
            },
        ),
    ]
