# Generated by Django 4.2.10 on 2024-03-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0010_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='BestellListe',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Investmittelplan',
        ),
        migrations.DeleteModel(
            name='Lagerliste',
        ),
        migrations.DeleteModel(
            name='TempLagerliste',
        ),
        migrations.DeleteModel(
            name='WebapplicationUser',
        ),
        migrations.DeleteModel(
            name='WebapplicationUserGroups',
        ),
        migrations.DeleteModel(
            name='WebapplicationUserUserPermissions',
        ),
    ]
