# Generated by Django 4.2.10 on 2024-03-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0012_bestellliste_investmittelplan_lagerliste_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempLagerliste',
        ),
    ]
