# Generated by Django 5.0.3 on 2024-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0014_lagerliste_ohne_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investmittelplan_Soll',
            fields=[
                ('ou', models.IntegerField(db_column='OU', primary_key=True, serialize=False)),
                ('investmittel_gesamt', models.DecimalField(db_column='Investmittel_gesamt', decimal_places=2, max_digits=8)),
                ('typ', models.CharField(db_column='Typ', max_length=50)),
                ('modell', models.CharField(db_column='Modell', max_length=50)),
                ('menge', models.IntegerField(db_column='Menge')),
                ('preis_pro_stück', models.DecimalField(db_column='Preis_pro_Stück', decimal_places=2, max_digits=6)),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
                ('investmittel_übrig_in_euro', models.DecimalField(blank=True, db_column='Investmittel_übrig_in_Euro', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Investmittelplan',
                'managed': False,
            },
        ),
    ]
