# Generated by Django 5.0.3 on 2024-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0015_investmittelplan_soll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_investmittelplan_Soll',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('typ', models.CharField(db_column='Typ', max_length=50)),
                ('modell', models.CharField(db_column='Modell', max_length=50)),
                ('menge', models.IntegerField(db_column='Menge')),
                ('preis_pro_stück', models.DecimalField(db_column='Preis_pro_Stück', decimal_places=2, max_digits=6)),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
            ],
            options={
                'db_table': 'Detail_Investmittelplan_Soll',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='investmittelplan_soll',
            table='Investmittelplan_Soll',
        ),
    ]
