# Generated by Django 5.0.3 on 2024-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0016_detail_investmittelplan_soll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('bestell_count', models.IntegerField(db_column='Bestell_Count')),
                ('bestell_achievement', models.IntegerField(db_column='Bestell_Achievement')),
                ('lager_count', models.IntegerField(db_column='Lager_Count')),
                ('lager_achievement', models.IntegerField(db_column='Lager_Achievement')),
            ],
            options={
                'db_table': 'Achievements',
                'managed': False,
            },
        ),
    ]
