# Generated by Django 5.1.1 on 2025-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0018_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investmittelplan_Alt',
            fields=[
                ('klinik_ou', models.IntegerField(primary_key=True, serialize=False)),
                ('investmittel_jahresanfang_in_euro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investmittel_übrig_in_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jahr', models.IntegerField(blank=True)),
            ],
        ),
    ]
