# Generated by Django 5.1.1 on 2025-02-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0019_investmittelplan_alt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investmittelplan_Alt',
        ),
    ]
