# Generated by Django 5.1.1 on 2025-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0020_delete_investmittelplan_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investmittelplan_Alt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klinik_ou', models.IntegerField(blank=True)),
                ('investmittel_jahresanfang_in_euro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investmittel_übrig_in_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jahr', models.IntegerField(blank=True)),
            ],
        ),
    ]
