# Generated by Django 5.1.1 on 2025-02-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0022_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
