# Generated by Django 5.1.1 on 2025-02-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0023_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Download/')),
                ('hochgeladen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
