# Generated by Django 5.1.1 on 2025-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0026_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='Upload/'),
        ),
    ]
