# Generated by Django 5.1.6 on 2025-03-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0027_alter_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
