# Generated by Django 5.1.6 on 2025-04-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0028_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='OU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ou', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investmittel_übrig', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investmittel_gesamt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('team', models.CharField(max_length=20)),
                ('bereich', models.CharField(max_length=20)),
                ('jahr', models.BigIntegerField()),
                ('typ', models.CharField(max_length=20)),
                ('ou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapplication.ou')),
            ],
        ),
    ]
