# Generated by Django 5.1.6 on 2025-04-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0029_ou_invest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invest',
        ),
        migrations.DeleteModel(
            name='OU',
        ),
    ]
