# Generated by Django 5.1.6 on 2025-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0030_delete_invest_delete_ou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investmittel_übrig', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investmittel_gesamt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('bereich', models.CharField(blank=True, max_length=40, null=True)),
                ('jahr', models.IntegerField()),
                ('typ', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Invest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OU',
            fields=[
                ('ou_id', models.IntegerField(db_column='OU_id', primary_key=True, serialize=False)),
                ('ou', models.IntegerField(db_column='OU')),
            ],
        ),
    ]
