# Generated by Django 5.1.6 on 2025-04-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0031_invest_ou'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ou',
            options={'managed': False},
        ),
    ]
