# Generated by Django 5.1.6 on 2025-04-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0032_alter_ou_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ou',
            table='OU',
        ),
    ]
