# Generated by Django 5.1.6 on 2025-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0033_alter_ou_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lager_Standard',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('sap_nr', models.CharField(db_column='SAP_Nr.', max_length=40)),
                ('name', models.CharField(db_column='Name', max_length=40)),
                ('modell', models.CharField(db_column='Modell', max_length=40)),
                ('spezifikation', models.TextField(blank=True, db_column='Spezifikation', null=True)),
                ('menge', models.IntegerField(db_column='Menge')),
                ('kommentar', models.TextField(blank=True, db_column='Kommentar', null=True)),
            ],
            options={
                'db_table': 'LagerStandard',
                'managed': False,
            },
        ),
    ]
