# Generated by Django 5.1.6 on 2025-06-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0034_lager_standard'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lager_standard',
            table='Lager_Standard',
        ),
    ]
