# Generated by Django 5.1.6 on 2025-06-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0036_lager_standard_entry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lager_standard_entry',
            table='Lager_Standard_Entry',
        ),
    ]
